CS50 problem sets 01
luisthieme/CS50-Harvard pull request #2
Opened 2023-08-04 07:41 UTC by luisthieme

2023-08-08 08:09 UTC, AlenoJankowsky requested changes

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/cash.c
> +}
```suggestion
}

```
Am Ende jeder Datei kommt immer eine new line, heißt EOF (End of File)

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/credit.c
> +    char x;
Bitte benenne deine Variablen immer so, dass man genau weiß wofür sie da sind, sogenannte "Speaking variables"

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/credit.c
> +    if((type1 + type2) % 10 != 0)
```suggestion
    sec_digit = atoi(&sec_digit_s);

    if((type1 + type2) % 10 != 0)
```
Nicht zu viel Platz dazwischen 😁

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/credit.c
> +        }else
```suggestion
        } else
```
Bitte hier ein Leerzeichen hinzufügen

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/credit.c
> +
```suggestion
```
Auch hier bitte unnötigen Platz einsparen 😁

2023-08-08 08:09 UTC, AlenoJankowsky commented on week1/mario-less.c
> +}
```suggestion
}

```
EOF

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/bulb.c
> +}
```suggestion
}

```
EOF 😁

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/bulb.c
> +
```suggestion
```

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/caesar.c
> +
```suggestion
```

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/caesar.c
> +
```suggestion
```

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/caesar.c
> +        // eig reicht der teil nach den && zeichen aus oder?
```suggestion
```
Bitte auch alle Kommentare löschen 😁

2023-08-08 08:09 UTC, AlenoJankowsky commented on week2/caesar.c
> +}
```suggestion
}

```
EOF 😁

2023-08-08 13:42 UTC, AlenoJankowsky commented on week2/caesar.c
> +
Not done yet 😁

2023-08-08 14:20 UTC, AlenoJankowsky requested changes

2023-08-08 14:20 UTC, AlenoJankowsky commented on week1/credit.c
> +    if((type1 + type2) % 10 != 0)
```suggestion
    sec_digit = atoi(&sec_digit_s);

    if((type1 + type2) % 10 != 0)
```

2023-08-08 14:20 UTC, AlenoJankowsky commented on week2/bulb.c
> +        putchar('\n');
```suggestion
        }

        putchar('\n');
```

2023-08-09 07:34 UTC, luisthieme commented on week2/readability.c
> +        {}
doch die beiden verhindern, dass das default case eintritt und die beiden symbole als letter gewertet werden. ich habe das ganze mal in ein switch case umgeschrieben dann wird der nutzen etwas deutlicher :)

2023-08-09 11:31 UTC, AlenoJankowsky approved these changes

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +    char input_c;
bitte gib dem einen genauen Namen -> nicht input_c

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +    int type1 = 0;
bitte gib dem einen genauen Namen -> was macht type?

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +    int type2 = 0;
bitte gib dem einen genauen Namen -> was macht type?

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +    int t = 0, remainder = 0, sum = 0, first_digit = 0, sec_digit = 0;
wir hatten darüber gesprochen das ein Buchstabe kein richtiger name für eine Variable ist :3

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +    char first_digit_s, sec_digit_s;
first_digit und sec_digit sind gute name. 
nur wenn du eine _s dahinter stellst, sagt es mir nicht was der Unterschied zu den normalen digits ist

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/credit.c
> +        input_c = input[temp];
was macht input c genau? ;)

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/mario-less.c
> +    int n;
n ist kein Name

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/mario-less.c
> +    for(int i = 0; i < n; i++)
int i 🙈

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/mario-less.c
> +        for(int k = 0; k < spaces; k++)
int k 👀

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/mario-less.c
> +        for(int j = 0; j < counter; j++)
int j 🥹

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week1/mario-less.c
> +        for(int j = 0; j < counter; j++)
int j 🥸

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/bulb.c
> +    for(int i = 0; i < lenght; i++)
int i 😞

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/bulb.c
> +        for (int j = 7; j >= 0; --j)
int j 😣

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/caesar.c
> +    for(int i = 0; i < lenght; i++)
int i 😖

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/readability.c
> +    scanf("%[^\n]%*c", text); // in c kann man mit der scanf funktion alleine nur einen string input annehmen bis zum ersten leerzeichen. um das zu umgehen muss man statt %s als placeholder %[^\n]%*c
wir benutzten keine Kommentare in unserem Code! Wir versuchen immer unseren Code so leserlich zu gestalten, dass wir keine Kommentare brauchen :)

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/readability.c
> +    for(int i = 0; i < lenght; i++)
int i >W<

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/readability.c
> +        char x = text[i];
char x 😫

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/readability.c
> +    double l = letters / (words / 100);
double l 😤

2023-08-16 07:35 UTC, AlexanderNeubert1 commented on week2/readability.c
> +    double s = sentences / (words / 100);
double s 😳

2023-08-16 08:25 UTC, luisthieme commented on week2/readability.c
> +    double l = letters / (words / 100);
name folgt aus aufgabenstellung

2023-08-16 08:25 UTC, luisthieme commented on week2/readability.c
> +    double s = sentences / (words / 100);
name folgt aus aufgabenstellung

2023-08-18 13:16 UTC, AlenoJankowsky commented
@AlexanderNeubert1 Bitte nochmal reviewen.

2023-08-23 09:55 UTC, AlexanderNeubert1 approved these changes

2023-08-29 06:25 UTC, merged