CS50 problem sets 02
luisthieme/CS50-Harvard pull request #3
Opened 2023-08-09 07:48 UTC by luisthieme

2023-08-09 14:13 UTC, AlexanderNeubert1 commented
Bitte gib nächste mal jeder Week einen eigenen PR ,)

2023-08-09 15:44 UTC, AlexanderNeubert1 commented
Bitte gib allen int i, int x, also jede Variable die du mit einem Buchstaben benannt hast, einen richtigen Namen.

2023-08-10 13:08 UTC, AlenoJankowsky requested changes

2023-08-10 13:08 UTC, AlenoJankowsky commented on .gitignore
> +.libcs50-11.0.2
```suggestion
.libcs50-11.0.2

```
EOF

2023-08-10 13:08 UTC, AlenoJankowsky commented on week2/substitution.c
> +
```suggestion
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week2/substitution.c
> +
```suggestion
```
Tut nichts?

2023-08-10 13:08 UTC, AlenoJankowsky commented on week2/substitution.c
> +
```suggestion
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week2/substitution.c
> +        return 1;
```suggestion
        printf("please enter only alphabetic characters!\n");

        return 1;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week2/wordle/test.c
> +}
```suggestion
}

```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +// Max number of candidates
```suggestion
```
Bitte alle Kommentare löschen

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +        return 1;
```suggestion
        printf("Usage: plurality [candidate ...]\n");

        return 1;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +        return 2;
```suggestion
        printf("Maximum number of candidates is %i\n", MAX);

        return 2;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +            return true;
```suggestion
            candidates[i].votes += 1;

            return true;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +    return false;
```suggestion
    }

    return false;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +    for(int i = 0; i < candidate_count; i++)
```suggestion
    }

    for(int i = 0; i < candidate_count; i++)
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/plurality.c
> +    return;
```suggestion
    }

    return;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +        return 1;
```suggestion
        printf("Usage: runoff [candidate ...]\n");

        return 1;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    // Check for invalid usage
```suggestion
```
Bitte alle Kommentare löschen

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +        return 2;
```suggestion
        printf("Maximum number of candidates is %i\n", MAX_CANDIDATES);

        return 2;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    for (int i = 0; i < candidate_count; i++)
```suggestion
    }

    for (int i = 0; i < candidate_count; i++)
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +                return 4;
```suggestion
                printf("Invalid vote.\n");

                return 4;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    return 0;
```suggestion
    }

    return 0;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +            return true;
```suggestion
            printf("%s\n", candidates[i].name);

            return true;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    return false;
```suggestion
    }

    return false;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    return min_votes;
```suggestion
    }

    return min_votes;
```

2023-08-10 13:08 UTC, AlenoJankowsky commented on week3/runoff.c
> +    return;
```suggestion
    }

    return;
```

2023-08-10 13:22 UTC, AlenoJankowsky requested changes

2023-08-10 13:22 UTC, AlenoJankowsky commented on week2/wordle/wordle.c
> +    if(won == true)
```suggestion
    if(won)
```

2023-08-10 13:22 UTC, AlenoJankowsky commented on week3/runoff.c
> +            if(candidates[i].votes != min && candidates[i].eliminated == false)
```suggestion
            if(candidates[i].votes != min && !candidates[i].eliminated)
```

2023-08-18 11:42 UTC, AlenoJankowsky requested changes

2023-08-18 11:42 UTC, AlenoJankowsky commented on week2/substitution.c
> +        return 1;
```suggestion
        printf("please enter excactly 26 letters!\n");

        return 1;
```

2023-08-18 11:42 UTC, AlenoJankowsky commented on week3/runoff.c
> +        }
```suggestion
        if (won) break;
```

2023-08-18 11:42 UTC, AlenoJankowsky commented on week3/runoff.c
> +        }
```suggestion
        if(candidates[counter].votes == min) candidates[counter].eliminated = true;
```

2023-08-18 11:42 UTC, AlenoJankowsky commented on week3/tideman.c
> +        }
```suggestion
        if(swap_counter == 0) sorted = true;
```

2023-08-18 11:42 UTC, AlenoJankowsky commented on week3/tideman.c
> +            }
```suggestion
            if(sources[inner_counter] != 99) is_source++;
```

2023-08-29 07:04 UTC, luisthieme commented on week2/substitution.c
> +        }
Das musst du mir nochmal erklären. Ich dachte wenn ich break benutze dann cancel ich den rest vom for-loop und dann würden ja die anderen Buchstaben nicht mehr auf Groß- oder Kleinschreibung geprüft werden.

2023-08-29 07:15 UTC, luisthieme commented on week3/runoff.c
> +        }
code formatter weigert sich xD

2025-01-16 09:59 UTC, closed without merging